# Generated by Django 5.1.7 on 2025-03-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_rename_order_orders_rename_proce_products_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={"verbose_name": "Позиция", "verbose_name_plural": "Позиции"},
        ),
        migrations.AlterModelOptions(
            name="orders",
            options={"verbose_name": "Заказ", "verbose_name_plural": "Заказы"},
        ),
        migrations.AlterModelOptions(
            name="products",
            options={"verbose_name": "Блюдо", "verbose_name_plural": "Блюда"},
        ),
        migrations.AlterField(
            model_name="orders",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="Время заказа"),
        ),
        migrations.AlterField(
            model_name="orders",
            name="updated_at",
            field=models.DateField(
                auto_now=True, verbose_name="Время изменения статуса"
            ),
        ),
    ]
